#!/bin/bash

# Firebase Setup Helper Script
# This script helps you create the .env.local file for Firebase configuration

echo "🔥 Firebase Setup Helper"
echo "========================"
echo ""
echo "This script will help you create your .env.local file."
echo "You'll need your Firebase project configuration values."
echo ""
echo "Get them from:"
echo "https://console.firebase.google.com/"
echo "→ Project Settings → Your apps → SDK setup and configuration"
echo ""
read -p "Press Enter to continue..."
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Cancelled. Your existing .env.local was not modified."
        exit 0
    fi
fi

echo ""
echo "Please enter your Firebase configuration values:"
echo ""

read -p "API Key: " api_key
read -p "Auth Domain (e.g., your-project.firebaseapp.com): " auth_domain
read -p "Database URL (e.g., https://your-project-default-rtdb.firebaseio.com): " database_url
read -p "Project ID: " project_id
read -p "Storage Bucket (e.g., your-project.appspot.com): " storage_bucket
read -p "Messaging Sender ID: " messaging_sender_id
read -p "App ID: " app_id

# Create .env.local file
cat > .env.local << EOF
# Firebase Configuration
# Generated by setup script on $(date)

VITE_FIREBASE_API_KEY=$api_key
VITE_FIREBASE_AUTH_DOMAIN=$auth_domain
VITE_FIREBASE_DATABASE_URL=$database_url
VITE_FIREBASE_PROJECT_ID=$project_id
VITE_FIREBASE_STORAGE_BUCKET=$storage_bucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$messaging_sender_id
VITE_FIREBASE_APP_ID=$app_id
EOF

echo ""
echo "✅ .env.local file created successfully!"
echo ""
echo "Next steps:"
echo "1. Restart your dev server: npm run dev"
echo "2. Check the browser console for Firebase connection status"
echo "3. Test on multiple devices to see real-time sync!"
echo ""
echo "📖 For detailed setup instructions, see FIREBASE_SETUP.md"
